name: meimErsterWorkflow

on:
  push:
    branches:
      - main

jobs:
  changed-job:
    runs-on: ubuntu-latest
    steps:
      - name: meinErsterStep
        run: echo "Hallo Welt!"
      - name: Abschied
        run: echo "Bye Bye!"

  zweiter-job:
    runs-on: ubuntu-latest
    needs: changed-job
    steps:
      - name: Datum anzeigen
        run: date


# Aufgabe1 hinzufügen von Job2 echo Bay Bay
#name: meimErsterWorkflow

#on:
 # push:
  #pull_request:

#jobs:
 # changed-job:
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: meinErsterStep
     #   run: echo "Hallo Welt!"
      #- name: Abschied
       # run: echo "Bye Bye!"

      


#name: meimErsterWorkflow

#on: push

#jobs:
 # meinEsterJob:
  # runs-on: ubuntu-latest
   #steps:
    #- name: meinErsterStep
     # run: echo "Hallo Weld!"
      


